# Set the following build variables via the Cloud Build:
# _REGION
# _SECRET_KEY
# _GS_BUCKET
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy
  args: 
    - functions
    - deploy
    - webhooks
    - --trigger-http
    - --allow-unauthenticated
    - --gen2
    - --runtime=nodejs20
    - --region=${_REGION}
    - --source=src/
    - --max-instances=1
    - --memory=128Mi
    - --set-env-vars 
    - SECRET_KEY=${_SECRET_KEY},GS_BUCKET=${_GS_BUCKET}
  env: 
    - 'SECRET_KEY=${_SECRET_KEY}'
    - 'GS_BUCKET=${_GS_BUCKET}'